### ISSUE TITLE
'See Other Sites' Needs Updating

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUTAHData#64]
For the Provo River, two of the sites are not showing up in the 'See Other Sites' dropdown in the upper right. I believe it is because they are relatively new sites: PR_ST_C and PR_ST_BA. The storm drain sites should probably show up for Red Butte Creek, too.

It would be best if this updated automatically whenever a new site is added.

**Comment by marioscience** [comment]
The problem with making it pull the sites automatic is that the sites that are shown are a selection of specified sites. I could do it so that it pulls the sites automatically but then all the sites in the database for the respective watershed will be shown, unless there is a field that can distinguish the sites.

**Comment by marioscience** [comment]
In the meantime, I have updated the dropdown list with the sites that were missing.

**Comment by AmberSJones** [comment]
PR_ST_BA is still missing from the Provo River list.

We can discuss options for automatically updating the list.

**Comment by marioscience** [comment]
PR_ST_BA was added to the list.
